//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoosePhone.cms.admin.product {
    
    
    public partial class ProductUC {
        
        /// <summary>
        /// LeftColumn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::ChoosePhone.cms.admin.product.LeftColumn LeftColumn;
    }
}
